# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190813_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator_sm',
            field=models.ImageField(default='avator/default.70x70.jpg', upload_to='avator/%Y%m%d', verbose_name='头像缩略图'),
        ),
    ]
