# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_userlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-create_time'], 'verbose_name': '用户日志', 'verbose_name_plural': '用户日志'},
        ),
    ]
